In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Food Waste data and research - by country.csv")

In [3]:
data

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,Very Low Confidence,4,Southern Asia,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,Very Low Confidence,8,Southern Europe,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,Very Low Confidence,12,Northern Africa,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,Low Confidence,20,Southern Europe,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,Very Low Confidence,24,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
...,...,...,...,...,...,...,...,...,...,...,...,...
209,Venezuela (Boliv. Rep. of),116,72,2065461,16,445994,28,788407,Very Low Confidence,862,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
210,Viet Nam,120,76,7346717,16,1508689,28,2666991,Very Low Confidence,704,South-eastern Asia,https://www.unep.org/resources/report/unep-foo...
211,Yemen,148,104,3026946,16,456099,28,806270,Very Low Confidence,887,Western Asia,https://www.unep.org/resources/report/unep-foo...
212,Zambia,122,78,1391729,16,279350,28,493822,Very Low Confidence,894,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
213,Zimbabwe,144,100,1458564,16,229059,28,404920,Very Low Confidence,716,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...

In [4]:
data.isna().sum()

Country                                   0
combined figures (kg/capita/year)         0
Household estimate (kg/capita/year)       0
Household estimate (tonnes/year)          0
Retail estimate (kg/capita/year)          0
Retail estimate (tonnes/year)             0
Food service estimate (kg/capita/year)    0
Food service estimate (tonnes/year)       0
Confidence in estimate                    0
M49 code                                  0
Region                                    0
Source                                    0
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country                                 214 non-null    object
 1   combined figures (kg/capita/year)       214 non-null    int64
 2   Household estimate (kg/capita/year)     214 non-null    int64
 3   Household estimate (tonnes/year)        214 non-null    int64
 4   Retail estimate (kg/capita/year)        214 non-null    int64
 5   Retail estimate (tonnes/year)           214 non-null    int64
 6   Food service estimate (kg/capita/year)  214 non-null    int64
 7   Food service estimate (tonnes/year)     214 non-null    int64
 8   Confidence in estimate                  214 non-null    object
 9   M49 code                                214 non-null    int64
 10  Region                                  214 non-null    object
 11  Source                                  214 non-null    object
dtypes: int64(8), object(4)
memory usage: 20.2+ KB

In [12]:
pk_rows = data[data['Country'] == 'Pakistan']   # stays a DataFrame

In [14]:
house_hold_tons = pk_rows['Household estimate (tonnes/year)']

In [15]:
house_hold_tons

144    15947645
Name: Household estimate (tonnes/year), dtype: int64

In [16]:
retail_est = pk_rows['Retail estimate (tonnes/year)']

In [17]:
retail_est

144    3387131
Name: Retail estimate (tonnes/year), dtype: int64

In [18]:
food_est = pk_rows['Food service estimate (tonnes/year)']

In [19]:
food_est

144    5987614
Name: Food service estimate (tonnes/year), dtype: int64

In [20]:
total_ton = house_hold_tons + retail_est + food_est

In [21]:
total_ton

144    25322390
dtype: int64

In [26]:
truck_capacity = 10  # Average capacity in tonnes
trucks_needed = total_ton / truck_capacity

In [36]:
print(f"House Hold: {house_hold_tons}")
print(f"Retail Estimated Waste: {retail_est}")
print(f"Food Service Waste: {food_est}")
#print(f"Trunk Needed: {int(trucks_needed)}")
print(f"Trucks Needed: {int(trucks_needed.iloc[0]):,}")

House Hold: 15947645
Retail Estimated Waste: 3387131
Food Service Waste: 5987614
Trucks Needed: 2,532,239

In [37]:
data

,Country,combined figures (kg/capita/year),Household estimate (kg/capita/year),Household estimate (tonnes/year),Retail estimate (kg/capita/year),Retail estimate (tonnes/year),Food service estimate (kg/capita/year),Food service estimate (tonnes/year),Confidence in estimate,M49 code,Region,Source
0,Afghanistan,126,82,3109153,16,594982,28,1051783,Very Low Confidence,4,Southern Asia,https://www.unep.org/resources/report/unep-foo...
1,Albania,127,83,238492,16,45058,28,79651,Very Low Confidence,8,Southern Europe,https://www.unep.org/resources/report/unep-foo...
2,Algeria,135,91,3918529,16,673360,28,1190335,Very Low Confidence,12,Northern Africa,https://www.unep.org/resources/report/unep-foo...
3,Andorra,123,84,6497,13,988,26,1971,Low Confidence,20,Southern Europe,https://www.unep.org/resources/report/unep-foo...
4,Angola,144,100,3169523,16,497755,28,879908,Very Low Confidence,24,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
...,...,...,...,...,...,...,...,...,...,...,...,...
209,Venezuela (Boliv. Rep. of),116,72,2065461,16,445994,28,788407,Very Low Confidence,862,Latin America and the Caribbean,https://www.unep.org/resources/report/unep-foo...
210,Viet Nam,120,76,7346717,16,1508689,28,2666991,Very Low Confidence,704,South-eastern Asia,https://www.unep.org/resources/report/unep-foo...
211,Yemen,148,104,3026946,16,456099,28,806270,Very Low Confidence,887,Western Asia,https://www.unep.org/resources/report/unep-foo...
212,Zambia,122,78,1391729,16,279350,28,493822,Very Low Confidence,894,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...
213,Zimbabwe,144,100,1458564,16,229059,28,404920,Very Low Confidence,716,Sub-Saharan Africa,https://www.unep.org/resources/report/unep-foo...